# Embedding in TensorFlow

In [144]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot
tf.test.gpu_device_name()

I0000 00:00:1732192815.143694    3603 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1732192815.143811    3603 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1732192815.143837    3603 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
I0000 00:00:1732192815.144087    3603 cuda_executor.cc:1001] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
2024-11-21 18:10:15.144108: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2112] Could not identify NUMA node of platform GPU id 0, defaulting to 0.  Your kernel may not have been built with NUMA support.

'/device:GPU:0'


2024-11-21 18:10:15.144174: I tensorflow/core/common_runtime/gpu/gpu_device.cc:2021] Created device /device:GPU:0 with 5563 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.9


In [145]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [146]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

Define in vacabulary size fot one hot encoding

In [147]:
voc_size=10000
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[1082, 885, 9095, 7436],
 [1082, 885, 9095, 3284],
 [1082, 8427, 9095, 2421],
 [4285, 2868, 9061, 4494, 5407],
 [4285, 2868, 9061, 4494, 9524],
 [8766, 1082, 6726, 9095, 6582],
 [1935, 553, 6081, 4494]]

#### word Embedding Representation

In [148]:

import numpy as np
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

Setting max sentence length

In [149]:
sent_length =8
# ! using padding in start
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1082  885 9095 7436]
 [   0    0    0    0 1082  885 9095 3284]
 [   0    0    0    0 1082 8427 9095 2421]
 [   0    0    0 4285 2868 9061 4494 5407]
 [   0    0    0 4285 2868 9061 4494 9524]
 [   0    0    0 8766 1082 6726 9095 6582]
 [   0    0    0    0 1935  553 6081 4494]]


Feature representation


In [150]:
dim=10
# ! features representation dim

In [151]:
from tensorflow.keras.layers import Embedding
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))

model.compile('adam','mse')

/home/arnav_bhatia/anaconda3/envs/py310/lib/python3.10/site-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [152]:
model.summary()

Model: "sequential_12"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_12 (Embedding)        │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [153]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step


array([[[-3.42291594e-02,  4.77897413e-02,  2.83894874e-02,
         -1.26175061e-02, -4.43079583e-02,  4.31761406e-02,
         -7.01807812e-03, -2.03403123e-02,  4.26223166e-02,
          2.59931795e-02],
        [-3.42291594e-02,  4.77897413e-02,  2.83894874e-02,
         -1.26175061e-02, -4.43079583e-02,  4.31761406e-02,
         -7.01807812e-03, -2.03403123e-02,  4.26223166e-02,
          2.59931795e-02],
        [-3.42291594e-02,  4.77897413e-02,  2.83894874e-02,
         -1.26175061e-02, -4.43079583e-02,  4.31761406e-02,
         -7.01807812e-03, -2.03403123e-02,  4.26223166e-02,
          2.59931795e-02],
        [-3.42291594e-02,  4.77897413e-02,  2.83894874e-02,
         -1.26175061e-02, -4.43079583e-02,  4.31761406e-02,
         -7.01807812e-03, -2.03403123e-02,  4.26223166e-02,
          2.59931795e-02],
        [-2.57433057e-02,  2.46999413e-03,  3.31448056e-02,
          4.92281206e-02, -1.14179365e-02,  4.11226489e-02,
         -1.57984346e-03,  1.18097067e-02, -2.816532

In [168]:
embedded_docs[:0].shape

(0, 8)

In [169]:
embedded_docs.shape

(7, 8)

In [179]:
model.predict(embedded_docs[:1]).shape

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step


(1, 8, 10)